

on:
  # push:                                           # 每次推送代码时触发 这个也合理 因为每个项目立项都要告诫一下自己 即使很多也没关系
  schedule:
    - cron: '20 1 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 2 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 3 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 4 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 5 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 6 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 7 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 8 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 9 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 10 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 11 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 12 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 13 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 14 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 15 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 16 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 17 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 18 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 19 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 20 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 21 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 22 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 23 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    - cron: '20 0 * * *'                          # 每天中国地区14:25（UTC时间 06:25）
    
  issues:
    types: [opened, edited, closed]                 # 当创建、编辑或关闭 Issue 时触发
  # issue_comment:
  #   types: [created]                              # 当回复 Issue 时触发

jobs:
  tell_suanfa_study_bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行脚本
      run: python main.py 1781591279@qq.com '算法学习方面' '今日刷了什么?学到什么?'
