

on:
  push:                    # 每次推送代码时触发 这个也合理 因为每个项目立项都要告诫一下自己 即使很多也没关系
  schedule:
    - cron: '25 6 * * *'   # 每天中国地区14:25（UTC时间 06:25）
jobs:
  tell_suanfa_study_bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 运行脚本
      run: python qqmail_tell.py 1781591279@qq.com '算法学习方面' '今日刷了什么?学到什么?'
